[project]
name = "signalcat"
version = "2.1.1"
authors = [
    { name="Shinjo Park", email="peremen@gmail.com" },
]
description = "Signaling Collection and Analysis Tool"
readme = "README.md"
license = {text = "GPL-2.0-or-later"}
classifiers = [
    "Operating System :: OS Independent",
]

requires-python = ">=3.10"
dependencies = [
    "pyusb>=1.0.2",
    "pyserial>=3.3",
    "bitstring>=4.0",
    "packaging>=19.0"
]
dynamic = [
  "urls",
]

[project.optional-dependencies]
fastcrc = [
    "libscrc>=1.8.0",
]

[project.scripts]
scat = "scat.main:scat_main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/scat"]

[tool.hatch.metadata.hooks.vcs.urls]
"Homepage" = "https://github.com/fgsect/scat"
"Bug Tracker" = "https://github.com/fgsect/scat/issues"
source_archive = "https://github.com/fgsect/scat/archive/{commit_hash}.zip"
